# Save changes to GitHub
backend:
  name: github
  repo: kee-org/www-kee-pm
  branch: beta

# Use the Editorial workflow - https://github.com/netlify/netlify-cms/blob/master/docs/editorial_workflow.md
#publish_mode: editorial_workflow

# Save image uploads to /img/uploads - https://gohugo.io/themes/creation/#static
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

# Collections
collections: # A list of collections the CMS should be able to edit
  # Used in routes, ie.: /admin/collections/:slug/edit
  - name: "article"
    # Used in the UI, ie.: "New Post"
    label: "News article"
    # The path to the folder where the documents are stored
    folder: "content/news"
    # Allow users to create new documents in this collection
    create: true
    # Filename template e.g. YYYY-MM-DD-title.md
    slug: "{{slug}}"
    # The fields each document in this collection have
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Tags", name: "tags", widget: "tags"}
